[project]
name = "predict-the-introverts-from-the-extroverts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["kaggle>=1.7.4.5", "pandas>=2.3.1", "scikit-learn>=1.7.0"]

[dependency-groups]
dev = ["ipykernel>=6.29.5"]
